### ISSUE TITLE
Como enviar mais de 1 item ?

### ISSUE THREAD

**Issue by mozgbrasil** [lucasmro/ClearSale#13]
Ola 

Boa Noite

Tudo bom

Gostaria de saber como faço para enviar mais de 1 item no XML

No modelo a seguir só demonstra o envio de 1 item

https://github.com/lucasmro/ClearSale/blob/master/examples/ecommerce-order-example.php#L36

**Comment by lucasmro** [comment]
Olá,

Você pode criar quantos itens quiser e adicioná-los na lista de itens do pedido utilizando o método addItem(), ou pode criar um array com todos os itens e depois utilizar o método setItem() para atribuir todos os itens de uma única vez.

Seguindo o exemplo de pedido criado aqui:
https://github.com/lucasmro/ClearSale/blob/master/examples/ecommerce-order-example.php#L40

Você pode fazer das duas maneiras que citei, veja os exemplos a seguir:

**Alternativa A:**

$item2 = Item::create(2, 'Cartão Micro Sd 64GB', 200.0, 1);
$order->addItem($item2);

$item3 = Item::create(3, 'Mouse', 85.0, 1);
$order->addItem($item3);

_**OBS:** Nesse caso já existe um item no pedido que foi criado junto com o pedido, após a utilização do método Order::createEcommerceOrder()._

**Alternativa B:**

$item1 = Item::create(1, 'Adaptador USB', 10.0, 1);
$item2 = Item::create(2, 'Cartão Micro Sd 64GB', 200.0, 1);
$item3 = Item::create(3, 'Mouse', 85.0, 1);

$items = array($item1, $item2, $item3);

$order->setItems($items);

**Referências:**
- https://github.com/lucasmro/ClearSale/blob/master/examples/ecommerce-order-example.php#L36
- https://github.com/lucasmro/ClearSale/blob/master/src/ClearSale/XmlEntity/SendOrder/Order.php#L696
- https://github.com/lucasmro/ClearSale/blob/master/src/ClearSale/XmlEntity/SendOrder/Order.php#L710

**Comment by mozgbrasil** [comment]
Obrigado
