### ISSUE TITLE
TransactionID 

### ISSUE THREAD

**Issue by elvispdosreis** [lucasmro/ClearSale#16]
Qual metodo eu utilizo para recuperar os seguintes dados TransactionID e Score?

**Comment by lucasmro** [comment]
Elvis,

Já tem algum tempo que não trabalho na evolução da biblioteca, mas pelo que analisei no código você pode conseguir essas informações seguindo os passos abaixo. Também escrevi um exemplo de código para facilitar.

1. Faça a requisição de análise do pedido e em seguida poderá obter o Transaction Id.
2. Atualize o pedido com o status do pagamento após a análise ("APROVADO" ou "REPROVADO") e depois poderá obter o score.

**OBS:** _Na implementação atual, o Score só pode ser obtido após informar a ClearSale sobre o status da cobrança.
Talvez seja possível melhorar esse código, mas precisaria consultar melhor a documentação da ClearSale.
Fique à vontade para enviar uma Pull Request se quiser contribuir com esta ou outras melhorias._

**Trecho de código exemplo:**

// Enviar pedido para análise
$clearSale = new ClearSaleAnalysis($environment);
$clearSale->analysis($order);

// Obter o Transaction Id
$packageStatus = $clearSale->getPackageStatus();
$transactionId = $packageStatus->getTransactionId();

// Obter o Score
$orderReturn = $clearSale->updateOrderStatusId($orderId, \ClearSale\ClearSaleAnalysis::APROVADO);
$score = $orderReturn->getScore();
