### ISSUE TITLE
Tag versioning for Composer compatibility

### ISSUE THREAD

**Issue by igorbrites** [lucasmro/ClearSale#3]
Would be great to add a tag to the repo, so the minimum compatibility can always be "stable".

**Comment by lucasmro** [comment]
Done! (v1.0.0)

**Comment by igorbrites** [comment]
Thanks!

**Comment by igorbrites** [comment]
Can you configure the Packagist to get your tag? =)

**Comment by lucasmro** [comment]
Done.
