### ISSUE TITLE
Missing GetOrdersStatus feature

### ISSUE THREAD

**Issue by tsantos84** [lucasmro/ClearSale#8]
I've inspected the source code and realize that there is no way to get the statuses of a list of orders. Such operation is documented at https://www.clearsale.com.br/integracaov2/service.asmx?op=GetOrdersStatus. Have you plan to add such feature soon?

**Comment by lucasmro** [comment]
Unfortunately, I don't have plans to add this feature soon.
Would you like to contribute with the library? Just send me a PR.
